# Generated by Django 5.0.1 on 2024-05-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0003_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='_class',
            new_name='class_field',
        ),
    ]
