# Generated by Django 5.0.1 on 2024-05-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0006_lesson_test_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
