# Generated by Django 5.0.1 on 2024-05-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0007_lesson_image_lesson_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='desscription',
            field=models.TextField(blank=True),
        ),
    ]
