# Generated by Django 5.0.1 on 2024-05-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0008_lesson_desscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='desscription',
            new_name='description',
        ),
    ]
