# Generated by Django 5.0.1 on 2024-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0011_scholarship_remove_test_user_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
