# Generated by Django 5.0.1 on 2024-05-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0012_scholarship_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='electric_onditioning',
            new_name='electric_conditioning',
        ),
    ]
